#Online Retail Dataset
#In this question we will analyse the Online Sales Data from Kaggle. This is a transnational 
#data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for 
#a United Kingdom (UK) based online store. Many customers of the store are wholesalers. First, 
#we call the libraries we need:
install.packages("sp")
install.packages("readxl")
install.packages("rworldmap")
install.packages("tidyverse")
install.packages("kableExtra")
install.packages("magrittr")
install.packages("forecast")

library(tseries)
library(base)
library(sp)
library(ggplot2) # for data visualization 
library(tidyverse) # for data wrangling 
library(rworldmap) # for creating maps 
library(readxl) # read Data 
library(lubridate) # for time series 
library(kableExtra) # for table outputs
library(dplyr)
library(magrittr)
library(datasets)
library(forecast)

#The data frame has 406,829 rows and 8 columns. Rows indicate different items ordered 
#in a transaction (invoice). Columns indicate the following:
# • InvoiceNo - Invoice (bill) number,
# • StockCode - Product (item) code,
# • Description - Product (item) name,
# • Quantity - The quantities of each product (item) per transaction, 
# • InvoiceDate - Invoice Date and time,
# • UnitPrice - Unit price, product price per unit in sterling, 
# • CustomerID - Customer number,
# • Country - Country name.

#Loading the dataset:
df <- read_excel("Online Retail.xlsx")
summary(df)
dim(df)
#Summary of data
head(df) %>%
kbl(caption = "Table 1: Head of Dataset       ", booktabs = T) %>% 
  kable_styling(latex_options = "striped")

#Data Analysing
sum(is.na(df$CustomerID))
sum(is.na(df$Invoice))

#Data cleaning
#Removing all the records with Customer ID is NA
df<-subset(df,df$CustomerID != "NA")

#Dataset containting Invoice number starting with C indicates cancelled order

df%>%filter(grepl('C',Invoice))

#Removed all the records with Invoice number starting with ‘C’ 
#as they are canceled Order and we don’t need them in revenue calculation
df<-df%>%filter(!grepl('C',df$Invoice))

#Removing time from the InvoiceDate column which are not being used in this analysis
df$InvoiceDate <- format(as.Date(df$InvoiceDate),"%Y-%m-%d")
df$InvoiceDate = as.Date(df$InvoiceDate)
typeof(df$InvoiceDate)
#Create new column for Year of Invoice to see yearly revenue
#df$Year_of_Invoice = format(as.Date(df$InvoiceDate), "%Y")
#df$Month= format (as.Date(df$InvoiceDate),"%m")
df$TotalPrice = df$Quantity * as.numeric(df$UnitPrice)
#df = df[ , -which(names(df) %in% c("year_of_Invoice"))]


df %>%
  select(Invoice, Country) %>%
  group_by(Country) %>%
  summarize(items=n()) %>%
  arrange(desc(items)) %>%
  kbl(caption = "Number of Transactions per Country", booktabs = T) %>% 
  kable_styling(latex_options = "striped")

#We will draw a bar chart to display the number of different invoices ordered from countries. 
#UK will dominate the chart as this is a UK-based company. To make the bar chart informative, 
#we remove UK from the data using filter() and display the number of invoices from 
#non-UK countries in an ordered fashion.

df %>%
  filter(Country != "United Kingdom") %>% # Remove UK
  ggplot() +
  geom_bar(mapping = aes(x = reorder(Country, table(Country)[Country])),
           fill="steelblue")+labs(x="Country",y="Number of Invoices",
                                  title="Number of Invoices from non-UK Orders")+ coord_flip() +
  theme_minimal()
  
#The above graphs displays that Germany, France and Ireland are top 3 countries where 
#online retail is working but it’s very low in comparison to UK. So, we should be 
  #focusing on UK only.
  



 

#Top Total revenue generated by each country:

df %>%
  select(TotalPrice, Country)%>% group_by(Country) %>%
  summarise(countrywise_totalrevenue = sum(TotalPrice)) %>% 
  arrange(desc(countrywise_totalrevenue)) %>%
  top_n(n = 10, wt = countrywise_totalrevenue) %>%
  kbl(caption = "Top 10 Total Revenue per Country", booktabs = T) %>% 
  kable_styling(latex_options = "striped")

#Bottom 10 Total revenue generated by each country:

df %>%
  select(TotalPrice, Country)%>% group_by(Country) %>%
  summarise(countrywise_totalrevenue = sum(TotalPrice)) %>% 
  arrange(countrywise_totalrevenue) %>%
  kbl(caption = "Underperforming Countries which generates lowest Revenue ", booktabs = T) %>% 
  kable_styling(latex_options = "striped")


#Now we will create the following map indicating the top 10 countries in terms of total revenue.
top20_countries <- df %>%
select(TotalPrice,Country) %>% group_by(Country) %>%
 summarize(countrywise_totalrevenue = sum(TotalPrice)) %>% 
 arrange(desc(countrywise_totalrevenue)) %>%
  top_n(n = 20, wt = countrywise_totalrevenue)

n <- joinCountryData2Map(top20_countries, joinCode="NAME", nameJoinColumn="Country")
mapCountryData(n, nameColumnToPlot="countrywise_totalrevenue", mapTitle="
Top 20 Countries Based on Total Revenue Based on Total")

#Zooming the Europe:
mapCountryData(n, nameColumnToPlot="countrywise_totalrevenue", mapRegion="Europe", 
mapTitle = "Top Europe Countries Based on Total Revenue")

#10 most valued customers in terms of money spent on orders from the company:
  df %>%
  select(TotalPrice,CustomerID) %>% 
    group_by(`CustomerID`) %>%
    summarise(customer_amount = sum(TotalPrice)) %>% 
    arrange(desc(customer_amount))%>%
    top_n(n = 10, wt = customer_amount) %>%
    kbl(caption = ".10 Most Valuable Customers", booktabs = T) %>% 
    kable_styling(latex_options = "striped")
 
  #Above graph represents the top 10 products which are mostly ordered by users. 
 #Look into 10 Top performing Product 
  df %>% 
    group_by(Description, StockCode) %>% 
    summarise(count = n()) %>% arrange(desc(count)) %>%
    head(10) %>% ggplot(aes(x = Description, y= count))+ 
    geom_bar(stat = 'identity', fill = "lightblue") + 
    coord_flip() + theme_classic()+ xlab("Products")+
    ylab("Number of products sold") + 
    ggtitle("Products most bought by Customers")
  
  #Monthly sales  
  
  df %>% select(TotalPrice, InvoiceDate) %>% 
    group_by(InvoiceDate)%>%
    summarise(Total_monthly_revenue = sum(TotalPrice)) %>% 
    ggplot(aes(InvoiceDate, Total_monthly_revenue ))+ 
    geom_line() + scale_x_date('Daily/Quarterly')+ylab("Revenue")+xlab("")+
    ggtitle("Daily Sales Trend")
  
  
  df %>% mutate(Year_of_Invoice = format(as.Date(df$InvoiceDate), "%Y"))%>%
    mutate(Month = format(as.Date(df$InvoiceDate), "%m")) %>% 
    group_by(Month, Year_of_Invoice)%>%
    summarise(Total_monthly_revenue = sum(TotalPrice)) %>% 
    arrange(desc(Total_monthly_revenue))%>%
    kbl(caption = ". Top performing months", booktabs = T) %>% 
    kable_styling(latex_options = "striped")
    
  df %>% mutate(Year_of_Invoice = format(as.Date(df$InvoiceDate), "%Y"))%>%
  mutate(Month = format(as.Date(df$InvoiceDate), "%m")) %>% 
    group_by(Month, Year_of_Invoice)%>%
    summarise(Total_monthly_revenue = sum(TotalPrice)) %>% 
    arrange(Total_monthly_revenue)%>%
    kbl(caption = ".   Worst performing months", booktabs = T) %>% 
    kable_styling(latex_options = "striped")
  
  
  
  #Create time series to Plot
  df_ts = ts(df[, c('TotalPrice')])
  df$clean_df_ts<-log(tsclean(df_ts))
  ggplot() + geom_line(data = df, aes(x = InvoiceDate, y = clean_df_ts)) + 
    ylab('Cleaned revenue Count')
  ## Don't know how to automatically pick scale for object of type ts. Defaulting to continuous.
  
  plot(diff(df$clean_df_ts))
  abline(a = 0 , b = 0)
  adf.test(diff(df$clean_df_ts), alternative = "stationary")
  
  
  #Total yearly Revenue countrywise 
  
 # df$year_of_Invoice = format(as.Date(df$InvoiceDate), "%Y")   
  df %>% mutate(TotalPrice = Quantity * as.numeric(Price)) %>% 
    group_by(year_of_Invoice)%>%
    summarise(Total_yearly_revenue = sum(TotalPrice)) %>% 
    ggplot(aes(x= Total_yearly_revenue, y= year_of_Invoice))+ geom_bar(stat = 'identity', fill = "lightblue") + 
    coord_flip() + theme_classic()+ xlab("Total revenue")+
    ylab("Years")+ ggtitle("Yearly Total Revenue")
  
  #Yearly total revenue
  
  
  #df$year_of_Invoice = format(as.Date(df$InvoiceDate), "%Y")   
  df %>% 
    mutate(Year_of_Invoice = format(as.Date(InvoiceDate), "%Y"))%>%
    mutate(Month = format(as.Date(InvoiceDate), "%m"))%>%
    mutate(Year_Month = format(as.Date(InvoiceDate), "%Y-%m"))%>%
    group_by(Month, Year_of_Invoice, Year_Month)%>%
    summarise(Total_yearly_revenue = sum(TotalPrice)) %>% 
    ggplot(aes(x= Year_Month, y=Total_yearly_revenue ))+ geom_bar(stat = 'identity', fill = "lightblue") + 
    coord_flip() + theme_classic()+ xlab("Month/Year")+
    ylab("Total Revenue")+ ggtitle("Total Monthly Revenue of the Store ")
  
  
  df %>% 
    mutate(Year_of_Invoice = format(as.Date(InvoiceDate), "%Y"))%>%
    mutate(Month = format(as.Date(InvoiceDate), "%m"))%>%
    mutate(Year_Month = format(as.Date(InvoiceDate), "%Y-%m"))%>%
    group_by(Month, Year_of_Invoice, Year_Month)%>%
    summarise(Total_yearly_revenue = sum(TotalPrice)) %>% 
    ggplot(aes(x= Year_Month, y=Total_yearly_revenue ))+ 
    geom_bar(stat = 'identity', fill = "lightblue") + 
    scale_y_date(date_breaks ="3", months,date_labels="%m-%Y")+
    coord_flip() + theme_classic()+ xlab("Month/Year")+
    ylab("Total Revenue")+ ggtitle("Total Monthly Revenue of the Store ")
  
  ggplot(df,aes(Invoice_Date, Price))+ geom_line() + 
    scale_x_date('Month')+ylab("Price")+xlab("")
  
  
  df %>% mutate(TotalPrice = Quantity * as.numeric(Price)) %>% 
    group_by(Invoice_Date)%>%filter(Invoice_Date>=2010-01-01)%>%
    summarise(Total_yearly_revenue = sum(TotalPrice)) %>% 
    plot(Total_yearly_revenue~as.date(Invoice_Date,"%y %m %d"), 
         type="l",xlab="Date",ylab ="Unit Sold")
 
summary(item)
item <- df%>% select(Description)
item
